/* Main.c file generated by New Project wizard
 *
 * Created:   ter ago 30 2022
 * Processor: PIC16C74B
 * Compiler:  CCS for PIC
 */

#include<Functions.c>






int main (void)
 { 
   ////////////////////////////////////////declaraciones/////////////////////////////
set_tris_a(0xff);
set_tris_d(0x00);
set_tris_b(0x00);

output_d(0x00); 
lcd_init () ; //Inicializacion del LCD
   
 
 PLC_CHECK_HDW_STATUS();  
  PLC_CHECK_MODE();
   

    
 /////////////////////////////////////ciclo//////////////////////////////////////////   
    while (1){
    
      
      /*Lectura de Entradas y actualizar imagen*/
       REFRESH_IMG_IN();
      
       
      /*Ejecucion del programa de usuario*/
  
 if (ERR_FLAG == 1){
   PLC_STOP();
      }
   else if (RUN_FLAG == 0 && ERR_FLAG == 0){
      PLC_PROG();
   }
   else if (RUN_FLAG == 1 && ERR_FLAG == 0){
      PLC_RUN();
   }
   else
      PLC_STOP();
  
       //Escritura de las Salidas
   REFRESH_OUT_IMG();
      
       
       //Chequeo de hard y soft
 PLC_CHECK_HDW_STATUS(); 
  PLC_CHECK_MODE();
       
       //Atencion a perifericos
   SHOW_PLC_STATE();
       
       }
   return 0;
 }   

